spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      restaurant-service:
        baseConfig: default
      mapsintegration:
        baseConfig: default
      payment-service:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      restaurant-service:
        baseConfig: default
      mapsintegration:
        baseConfig: default
      payment-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      restaurant-service:
        baseConfig: default
      mapsintegration:
        baseConfig: default
      payment-service:
        baseConfig: default
